### ISSUE TITLE
[BUG] PreAuthenticating event does not fire when connecting to a server with whitelist enabled

### ISSUE THREAD

**Issue by Jesus-QC** [Exiled-Official/EXILED#73]
**[<img src="https://avatars.githubusercontent.com/u/45165615?s=17&v=4" width="17" height="17"> @Misaka-ZeroTwo](https://www.github.com/Misaka-ZeroTwo)** cloned issue [Exiled-Team/EXILED#1749](https://www.github.com/Exiled-Team/EXILED/issues/1749) on 2023-04-21: 

> **Describe the bug**
> 
> Per title
> 
> 
> 
> Reported by: @Ficus-x 
> 
>

**Comment by Jesus-QC** [comment]
**[<img src="https://avatars.githubusercontent.com/u/10914157?s=17&v=4" width="17" height="17"> @joker-119](https://www.github.com/joker-119)** [commented](https://www.github.com/Exiled-Team/EXILED/issues/1749#issuecomment-1518453486) on 2023-04-22: 

> While this is P1, the only way to fix it would be by re-adding a preauth patch for this event. Idk why it was removed in the first place but there's a lot that could go wrong with doing so, thus this P1 will not be considered blocking.

**Comment by Jesus-QC** [comment]
**[<img src="https://avatars.githubusercontent.com/u/45165615?s=17&v=4" width="17" height="17"> @Misaka-ZeroTwo](https://www.github.com/Misaka-ZeroTwo)** [commented](https://www.github.com/Exiled-Team/EXILED/issues/1749#issuecomment-1585618619) on 2023-06-10: 

> Re-open due to the fix being broken.

**Comment by Jesus-QC** [comment]
**[<img src="https://avatars.githubusercontent.com/u/66829532?s=17&v=4" width="17" height="17"> @louis1706](https://www.github.com/louis1706)** [commented](https://www.github.com/Exiled-Team/EXILED/issues/1749#issuecomment-1760556181) on 2023-10-13: 

> I will look at this after the next Release of NW since they will entirely rewrite this method

**Comment by Vladislav-CS** [comment]
https://github.com/Exiled-Team/EXILED/issues/1749#issuecomment-2235430552
